server:
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/exa-grad/exam-service}
  error:
    include-message: always

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,readiness,liveness,prometheus
  endpoint:
    health:
      probes:
        enabled: true

spring:
  application:
    name: ASE-UserService

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
