apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: exam-service
  namespace: ase-14
  annotations:
    traefik.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: traefik
  rules:
    - host: sau-portal.de
      http:
        paths:
          - path: /exa-grad/exam-service
            pathType: Prefix
            backend:
              service:
                name: exam-service
                port:
                  number: 80
