apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/agile-software-engineering-25/team-14-backend-examination-office
    newTag: latest
