apiVersion: v1
kind: Service
metadata:
  name: exam-service
  namespace: ase-14
  labels:
    app: exam-service
spec:
  selector:
    app: exam-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
